[project]
name = "wallet"
version = "0.1.0"
description = "Projeto para cumprir o desafio para a vaga de desenvolvedor backend sênior da IplanRio."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
